[package]
name = "spamm_alt_stub"
version = "0.1.0"
edition = "2021"
license = "CC-BY-NC-4.0"
description = "Minimal Address Lookup Table program stub for Mollusk tests (Create + Extend only)."

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.2.1"
solana-address-lookup-table-interface = { version = "2.2.2", default-features = false, features = [
   "bincode",
   "bytemuck",
] }

[profile.release]
debug = 1
